name: Keep Render Service Alive
on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:  # يسمح بالتشغيل اليدوي

jobs:
  ping-render:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render
        run: |
          echo "Sending request..."
          curl -X GET "https://render-telegram-bot-823k.onrender.com"
          echo -e "\nDone!"
